### ISSUE TITLE
Subtlety: font-weight:bold on h1, h2 do not affect display

### ISSUE THREAD

**Issue by jzhu01** [Mabonzo/prj-rev-bwfs-dasmoto#1]
See line: https://github.com/Mabonzo/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/DasmotosArtsAndCrafts/resources/css/style.css#L11
 
Does not change how the h1 is displayed.

**Comment by Mabonzo** [comment]
Fix: removed redundant font-weight declaration from heading selectors
