### ISSUE TITLE
Subtlety: Alternative to using classes for each section heading

### ISSUE THREAD

**Issue by jzhu01** [Mabonzo/prj-rev-bwfs-dasmoto#3]
Such as these: https://github.com/Mabonzo/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/DasmotosArtsAndCrafts/resources/css/style.css#L32-L43 

Since they are only used once and refer to only one element, it would be better to use an ID.

**Comment by Mabonzo** [comment]
Fix: changed the h2 styling selectors from classes to ids
