### ISSUE TITLE
Subtlety: Margin

### ISSUE THREAD

**Issue by jzhu01** [Mabonzo/prj-rev-bwfs-dasmoto#4]
On banner, you can implement a left: -0.5px to remove the extra space, so you don't need to do width:100%

See line: https://github.com/Mabonzo/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/DasmotosArtsAndCrafts/resources/css/style.css#L30

**Comment by Mabonzo** [comment]
Fix: changed **width** declaration on `.banner` and `.text-background` selectors to **left** and **right** declarations
