### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by jzhu01** [Mabonzo/prj-rev-bwfs-dasmoto#6]
Great job on this project - I really loved your footer, as well as your addition of a background texture. In terms of improvement, I recommend removing the font-weight:bold on your h1s and h2s, as well as implementing IDs for the section headings.

If you’re in the mood for a challenge, I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Feel free to reach out and let us know if you have any questions, good luck!

**Comment by Mabonzo** [comment]
I want to leave this project as is, as a milestone to look back on, but I will try to use more Responsive Web Design techniques as I go through the *CodeAcademy* course. Thank you for the comments and critiques!
